### ISSUE TITLE
Make plot_frames_hidpi target optional

### ISSUE THREAD

**Issue by usert5432** [LS4GAN/toyzero#3]
The `plot_frames_hidpi` target (is run as a part of `all_frames` target) requires having `poppler` built with almost all dependencies. `poppler` is a very heavy dependency which severely limits the number of systems where `toyzero` package can be run with the default configuration.

Since, there is no need to make hidpi plots by default (or any plots for that matter), I believe it would be beneficial not to run `plot_frames_hidpi` in the default configuration.

**Comment by brettviren** [comment]
I hadn't noticed this dependency.  I guess it is provided implicitly by Ubuntu and Debian or the `pip install` quietly satisfied it.

I think we can easily provide a new `all_data` rule that depends only on a minimum of other rule outputs so as to only make the final "image" files.  Users that do not want to provide a full working environment but just want images can then build that rule.

If you want to add this rule yourself, please go for it.  O.w. I'll add it next time I visit this work.
